### ISSUE TITLE
Problem running

### ISSUE THREAD

**Issue by mark3435** [further-reading/scraping-browser#22]
Hi, I am a beginner. I have a problem after installing scrapy-gui in Linuxmint 
I successfully installed 
`pip install scrapy_gui`

I tried in Python shell
`import scrapy_gui`
got:
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/user/.local/lib/python3.8/site-packages/scrapy_gui/__init__.py", line 2, in <module>
>     from .browser import open_browser
>   File "/home/user/.local/lib/python3.8/site-packages/scrapy_gui/browser.py", line 7, in <module>
>     from .browser_window.browser import QtBrowser
>   File "/home/user/.local/lib/python3.8/site-packages/scrapy_gui/browser_window/browser.py", line 4, in <module>
>     from PyQt5.QtWebEngineWidgets import QWebEngineView
> ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'
> 

`scrapy_gui.open_browser()`

>   File "<stdin>", line 1, in <module>
> ImportError: No module named scrapy_gui

Any help appreciated.

**Comment by further-reading** [comment]
Hmm, based on the error there's something weird with the PyQt5 Web engine widgets. I just installed this on a fresh ubuntu 20 install so it might be OS dependent.

Can you tell me what happens when you run `pip install PyQtWebEngine==5.14.0`?

**Comment by mark3435** [comment]
Hi
`Successfully installed PyQtWebEngine-5.14.0`
But then when I try to start scrapi gui the same errors occurred.

I also tried in fresh ubuntu 20 (in VM) and got the same errors as in linux mint.

**Comment by further-reading** [comment]
Can you run `pip freeze` and share the result here?

**Comment by mark3435** [comment]
```
allure-pytest==2.8.17
allure-python-commons==2.8.17
apipkg==1.5
apt-clone==0.2.1
apturl==0.5.2
attrs==19.3.0
autokey==0.95.10
Automat==0.8.0
backcall==0.2.0
beautifulsoup4==4.9.1
blinker==1.4
boto==2.49.0
Brlapi==0.7.0
brython==3.8.9
ccsm==0.9.14.1
certifi==2020.6.20
cffi==1.14.1
chardet==3.0.4
cliapp==1.20180812.1
Click==7.0
cmdtest==0.32+git
colorama==0.4.3
command-not-found==0.3
commonmark==0.9.1
compizconfig-python==0.9.14.1
configobj==5.0.6
constantly==15.1.0
coverage==5.2.1
crudini==0.9.3
cryptography==3.0
cssselect==1.1.0
cupshelpers==1.0
dbus-python==1.2.16
decorator==4.4.2
defer==1.0.6
deluge==2.0.3
distro==1.4.0
entrypoints==0.3
execnet==1.7.1
flake8==3.8.3
gpg===1.13.1-unknown
grpcio==1.16.1
h5py==2.10.0
httplib2==0.14.0
hyperlink==19.0.0
idna==2.10
ifaddr==0.1.6
incremental==16.10.1
iniconfig==1.0.1
iniparse==0.4
ipdb==0.13.3
ipython==7.17.0
ipython-genutils==0.2.0
itemadapter==0.1.0
itemloaders==1.0.2
jedi==0.17.2
jmespath==0.10.0
joblib==0.14.0
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
keyring==18.0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
louis==3.12.0
lxml==4.5.0
Mako==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.0
mccabe==0.6.1
more-itertools==8.4.0
mpi4py==3.0.3
msedge-selenium-tools==3.141.2
netifaces==0.10.4
nose==1.3.7
numpy==1.17.4
oauthlib==3.1.0
onboard==1.4.1
packaging==20.4
parameterized==0.7.4
parsel==1.6.0
parso==0.7.1
pdfminer.six==20200726
pexpect==4.6.0
pickleshare==0.7.5
Pillow==7.0.0
pluggy==0.13.1
prompt-toolkit==3.0.6
Protego==0.1.16
protobuf==3.6.1
proxyscrape==0.3.0
psutil==5.5.1
py==1.9.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycairo==1.16.2
pycodestyle==2.6.0
pycparser==2.20
pycrypto==2.6.1
pycups==1.9.73
pycurl==7.43.0.2
PyDispatcher==2.0.5
pyflakes==2.2.0
Pygments==2.6.1
PyGObject==3.36.0
PyHamcrest==1.9.0
PyICU==2.4.2
pyinotify==0.9.6
PyJWT==1.7.1
PyMySQL==0.10.0
PyNaCl==1.3.0
pyOpenSSL==19.1.0
pyotp==2.4.0
pyparsing==2.4.6
pyparted==3.11.2
PyQt5==5.14.1
PyQt5-sip==12.8.0
PyQtWebEngine==5.14.0
PySocks==1.6.8
pytest==6.0.1
pytest-cov==2.10.0
pytest-forked==1.3.0
pytest-html==2.0.1
pytest-metadata==1.10.0
pytest-ordering==0.6
pytest-rerunfailures==9.0
pytest-xdist==1.34.0
python-apt==2.0.0+ubuntu0.20.4.1
python-debian===0.1.36ubuntu1
python-libtorrent==1.1.13
python-xapp==2.0.1
python-xlib==0.23
pyxdg==0.26
PyYAML==5.3.1
queuelib==1.5.0
rencode==1.0.6
reportlab==3.5.34
requests==2.24.0
requests-unixsocket==0.2.0
rich==5.1.2
scikit-learn==0.22.2.post1
scipy==1.3.3
Scrapy==2.3.0
scrapy-GUI==1.2
SecretStorage==2.3.1
selenium==3.141.0
seleniumbase==1.46.3
service-identity==18.1.0
sessioninstaller==0.0.0
setproctitle==1.1.10
setuptools-scm==4.1.2
simplejson==3.16.0
sip==4.19.21
six==1.14.0
sortedcontainers==2.2.2
soupsieve==2.0.1
supervisor==4.1.0
system-service==0.3
systemd-python==234
Theano==1.0.4
toml==0.10.1
torbrowser-launcher==0.3.2
traitlets==4.3.3
ttystatus==0.38
Twisted==18.9.0
typing-extensions==3.7.4.2
ubuntu-advantage-tools==20.3
ubuntu-drivers-common==0.0.0
ufw==0.36
Unidecode==1.1.1
urllib3==1.25.10
w3lib==1.22.0
wadllib==1.3.3
wcwidth==0.2.5
xkit==0.0.0
zeroconf==0.24.4
zope.interface==4.7.1

```

**Comment by further-reading** [comment]
So that's odd, it shows that you have PyQtWebEngine installed so the ModuleNotFoundError: No module named 'PyQt5.QtWebEngineWidgets'` error should not be occurring. 

I even manually installed the same versions of scrapy_gui, pyqt5 and PyQtWebEngine that you have and no error occurred. 

My best guess is that one of the other packages is messing around with PyQt5 in a way that breaks the Web engine. Try creating a virtual environment and only install scrapy + scrapy_gui in it and see if it works.

**Comment by mark3435** [comment]
This is the result from fresh ubuntu 20
`pip3 freeze`

```
apturl==0.5.2
bcrypt==3.1.7
beautifulsoup4==4.9.1
blinker==1.4
Brlapi==0.7.0
certifi==2019.11.28
chardet==3.0.4
Click==7.0
colorama==0.4.3
command-not-found==0.3
cryptography==2.8
cssselect==1.1.0
cupshelpers==1.0
dbus-python==1.2.16
defer==1.0.6
distro==1.4.0
distro-info===0.23ubuntu1
duplicity==0.8.12.0
entrypoints==0.3
fasteners==0.14.1
future==0.18.2
httplib2==0.14.0
idna==2.8
keyring==18.0.1
language-selector==0.1
launchpadlib==1.10.13
lazr.restfulclient==0.14.2
lazr.uri==1.0.3
lockfile==0.12.2
louis==3.12.0
lxml==4.5.2
macaroonbakery==1.3.1
Mako==1.1.0
MarkupSafe==1.1.0
monotonic==1.5
netifaces==0.10.4
oauthlib==3.1.0
olefile==0.46
paramiko==2.6.0
parsel==1.6.0
pexpect==4.6.0
Pillow==7.0.0
protobuf==3.6.1
pycairo==1.16.2
pycups==1.9.73
PyGObject==3.36.0
PyJWT==1.7.1
pymacaroons==0.13.0
PyNaCl==1.3.0
PyQt5==5.15.0
PyQt5-sip==12.8.0
PyQtWebEngine==5.15.0
pyRFC3339==1.1
python-apt==2.0.0+ubuntu0.20.4.1
python-dateutil==2.7.3
python-debian===0.1.36ubuntu1
pytz==2019.3
pyxdg==0.26
PyYAML==5.3.1
reportlab==3.5.34
requests==2.22.0
requests-unixsocket==0.2.0
scrapy-GUI==1.2
SecretStorage==2.3.1
simplejson==3.16.0
six==1.14.0
soupsieve==2.0.1
systemd-python==234
ubuntu-advantage-tools==20.3
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.8
usb-creator==0.3.7
w3lib==1.22.0
wadllib==1.3.3
xkit==0.0.0
```

`scrapy_gui.open_browser()`

```
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
Aborted (core dumped)
```

**Comment by further-reading** [comment]
So good news is that the package is importing fine now! However, there is a general compatibility issue between pyqt5 and the version of ubuntu you're using. 

This would impact every pyqt5 based UI so chances are there's a standard way to fix it. I'd suggest looking for general solutions for that specific error. I expect you only need to install one of the listed plugins.

**Comment by mark3435** [comment]
I try again from the start. Where this command go? in Python shell?
`import scrapy_gui`
